version: "3.8"

services:
  app:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: mf-cats-dev
    image: mf-cats-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3002:3000